export const COUPON_CODES = {
  BFRIDAY: "BFRIDAY",
  SUMMER_DISCOUNT: "SUMMER_DISCOUNT",
  WINTER_SPECIAL: "WINTER_SPECIAL",
  NEW_YEAR_DISCOUNT: "NEW_YEAR_DISCOUNT",
  BLACK_FRIDAY_DISCOUNT: "BLACK_FRIDAY_DISCOUNT",
} as const;

export type CouponCode = keyof typeof COUPON_CODES;
